C     WRITE A FORTRAN PROGRAM TO DETERMINE THE ROOTS OF QUARDEATIC EQUATION.
C     WRITTEN BY SK SALMAN PARBHAGE ROLLNO_PHY212050

      PROGRAM QUADRATIC
      IMPLICIT NONE
      REAL:: A,B,C,D,ROOT1,ROOT2
      WRITE(*,*)'ENTER THE VALUE OF A, B , C'
      READ(*,*) A,B,C
      D = B**2-4*A*C
      
C      CASE1: FOR REAL AND EQUAL ROOTS
      IF (D==0) THEN
      PRINT *,'ROOTS ARE REAL AND EQUAL'
      ROOT1 = -B/(2*A)
      PRINT*,'REAL AND EQUAL ROOTS IS =', ROOT1
c      REAL BUT UNEQUAL ROOTS
      ELSEIF(D>0) THEN
      PRINT *,'ROOTS ARE REAL AND UNEQUAL'
      ROOT1 = (-B + SQRT(D))/(2*A)
      ROOT2 = (-B - SQRT(D))/(2*A)
      PRINT *,'REAL AND EQUAL ROOTS ARE = ', ROOT1,ROOT2
c      COMPLEX ROOTS
      ELSEIF (D<0) THEN
      PRINT *, 'ROOTS ARE UQUAL AND COMPLEX'
      PRINT *,'ROOTS ARE=',-B/2*A,'+i',(SQRT(ABS(D)))/2*A,'&',-B/2*A,'-i',(SQRT(ABS(D)))/2*A
      ENDIF
      END PROGRAM
